CREATE TABLE IF NOT EXISTS cafestore (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50),

  address_line1 VARCHAR(200) NOT NULL,
  address_line2 VARCHAR(200),

  city VARCHAR(80) NOT NULL,
  country VARCHAR(80),

  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),

  open_time TIME NOT NULL,
  close_time TIME NOT NULL,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMP NOT NULL DEFAULT (timezone('UTC', now()))
);

ALTER TABLE cafestore
  ADD CONSTRAINT chk_cafestore_latitude  CHECK (latitude  IS NULL OR (latitude  BETWEEN -90 AND 90)),
  ADD CONSTRAINT chk_cafestore_longitude CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180));
